sudo: false
language: node_js
node_js:
  - "7.7.1"

branches:
  only:
  - master
  - develop

before_install:
  - npm config set spin false

install:
  - npm uninstall typescript
  - npm install -g typescript
  - npm install --development

cache:
  directories:
    - "node_modules"

before_script:
  - tsc

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)